apiVersion: apps/v1
kind: Deployment
metadata:
  name: UserList
  labels:
    app: UserList
spec:
  replicas: 1
  selector:
    matchLabels:
      app: UserList
  template:
    metadata:
      labels:
        app: UserList
    spec:
      containers:
        - name: UserList
          image: username/UserList:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5