---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: MeetingRoom
  labels:
    app: MeetingRoom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MeetingRoom
  template:
    metadata:
      labels:
        app: MeetingRoom
    spec:
      containers:
        - name: MeetingRoom
          image: username/MeetingRoom:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: UserList
  labels:
    app: UserList
spec:
  replicas: 1
  selector:
    matchLabels:
      app: UserList
  template:
    metadata:
      labels:
        app: UserList
    spec:
      containers:
        - name: UserList
          image: username/UserList:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ReservationApp
  labels:
    app: ReservationApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ReservationApp
  template:
    metadata:
      labels:
        app: ReservationApp
    spec:
      containers:
        - name: ReservationApp
          image: username/ReservationApp:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Alarm
  labels:
    app: Alarm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Alarm
  template:
    metadata:
      labels:
        app: Alarm
    spec:
      containers:
        - name: Alarm
          image: username/Alarm:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: View
  labels:
    app: View
spec:
  replicas: 1
  selector:
    matchLabels:
      app: View
  template:
    metadata:
      labels:
        app: View
    spec:
      containers:
        - name: View
          image: username/View:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: MeetingRoom
  labels:
    app: MeetingRoom
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: MeetingRoom


---


apiVersion: v1
kind: Service
metadata:
  name: UserList
  labels:
    app: UserList
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: UserList


---


apiVersion: v1
kind: Service
metadata:
  name: ReservationApp
  labels:
    app: ReservationApp
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ReservationApp


---


apiVersion: v1
kind: Service
metadata:
  name: Alarm
  labels:
    app: Alarm
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Alarm


---


apiVersion: v1
kind: Service
metadata:
  name: View
  labels:
    app: View
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: View

